### ISSUE TITLE
[Bug Report] Delay on window close

### ISSUE THREAD

**Issue by Patrock404** [klangman/CassiaWindowList#6]
I've noticed since the most recent update that there is a short but noticeable delay between closing a window that is not pinned to the panel, and the icon for that window disappearing.

**Comment by klangman** [comment]
@Patrock404 Thanks for the report!!  

I think I was animating the label on window close even when the label was not present. The "Label animation time" is being used to decide how long to spending shrinking the label before removing the button entirely. By default that would be 1/2 a second. You should be able to fix this by using setting the "Label animation time" to 0 in the config under the "Labels" tab, or you can update your copy with the latest from Github to get the following commit.

The fix is in this commit: https://github.com/klangman/CassiaWindowList/commit/a68d73caae434fe2fa2983f5b3f41ea298854342

When/if you have a chance to update to get this fix, please let me know if it addresses your issue, and thanks again for reporting the issue!!

**Comment by Patrock404** [comment]
You were right, while I'm not able to turn the label animation time to 0 (the minimum seems to be 5), I fixed the issue by disabling the "Animate Label" option.

**Comment by klangman** [comment]
Oh, ya disabling the animation is even better then what I was thinking. Come to think of it, I am not sure why it's even an option, just having an animation where 0 is the minimum would mean that we don't even need the disable animation option in the config.  In any case, with the fix, even with animation enabled and set to a large time value it will not cause a delay if there is no label to animate.
